-- Gerado por scripts/build-exercise-catalog.mjs. Não edite à mão.
-- Fonte: github.com/yuhonas/free-exercise-db (Unlicense, domínio público).

insert into public.exercises (slug, name, equipment, primary_muscle, media_start_path, media_end_path, cue)
values
  ('hip-thrust-barra', 'Hip thrust com barra', 'barra', 'Glúteo máximo', '/exercicios/hip-thrust-barra-0.jpg', '/exercicios/hip-thrust-barra-1.jpg', 'Não encoste o glúteo no chão. Um segundo de aperto no topo.'),
  ('elevacao-pelvica-maquina', 'Elevação pélvica na máquina', 'máquina', 'Glúteo máximo', '/exercicios/elevacao-pelvica-maquina-0.jpg', '/exercicios/elevacao-pelvica-maquina-1.jpg', 'Mesma cadência da barra. A carga não se compara com a do hip thrust livre.'),
  ('rdl-halteres', 'Levantamento terra romeno', 'halteres', 'Posterior de coxa', '/exercicios/rdl-halteres-0.jpg', '/exercicios/rdl-halteres-1.jpg', 'Quadril para trás, halteres colados na perna. Pare antes de perder a lombar neutra.'),
  ('pull-through', 'Pull-through na polia', 'polia', 'Glúteo máximo', '/exercicios/pull-through-0.jpg', '/exercicios/pull-through-1.jpg', 'Ensina o padrão do terra romeno sem carga na coluna.'),
  ('extensao-45-gluteo', 'Extensão 45° foco glúteo', 'máquina', 'Glúteo máximo', '/exercicios/extensao-45-gluteo-0.jpg', '/exercicios/extensao-45-gluteo-1.jpg', 'Pés abertos e virados para fora, queixo baixo. Suba só até alinhar o quadril.'),
  ('cadeira-flexora-sentada', 'Cadeira flexora sentada', 'máquina', 'Posterior de coxa', '/exercicios/cadeira-flexora-sentada-0.jpg', '/exercicios/cadeira-flexora-sentada-1.jpg', 'Sentada alonga mais que deitada. Dois segundos na volta.'),
  ('coice-polia', 'Coice na polia', 'polia', 'Glúteo máximo', '/exercicios/coice-polia-0.jpg', '/exercicios/coice-polia-1.jpg', 'Tronco à frente, um segundo de aperto, sem hiperestender a lombar.'),
  ('coice-maquina', 'Coice na máquina', 'máquina', 'Glúteo máximo', '/exercicios/coice-maquina-0.jpg', '/exercicios/coice-maquina-1.jpg', 'Tronco à frente, um segundo de aperto.'),
  ('abducao-polia', 'Abdução em pé na polia', 'polia', 'Glúteo médio', '/exercicios/abducao-polia-0.jpg', '/exercicios/abducao-polia-1.jpg', 'Três segundos na volta. Só sobe carga quando fechar 20 repetições.'),
  ('cadeira-abdutora', 'Cadeira abdutora', 'máquina', 'Glúteo médio', '/exercicios/cadeira-abdutora-0.jpg', '/exercicios/cadeira-abdutora-1.jpg', 'Tronco inclinado uns 30° à frente: é o que leva o estímulo para o glúteo médio.'),
  ('goblet-squat', 'Goblet squat', 'halteres', 'Quadríceps', '/exercicios/goblet-squat-0.jpg', '/exercicios/goblet-squat-1.jpg', 'Profundidade completa, joelhos na linha dos pés.'),
  ('agachamento-livre', 'Agachamento livre', 'barra', 'Quadríceps', '/exercicios/agachamento-livre-0.jpg', '/exercicios/agachamento-livre-1.jpg', 'Profundidade completa. Nunca até a falha.'),
  ('hack-squat', 'Agachamento hack', 'máquina', 'Quadríceps', '/exercicios/hack-squat-0.jpg', '/exercicios/hack-squat-1.jpg', 'Lombar colada no encosto o tempo todo.'),
  ('leg-press-45', 'Leg press 45°', 'máquina', 'Quadríceps', '/exercicios/leg-press-45-0.jpg', '/exercicios/leg-press-45-1.jpg', 'Pés na altura média, sem tirar a lombar do encosto.'),
  ('cadeira-extensora', 'Cadeira extensora', 'máquina', 'Quadríceps', '/exercicios/cadeira-extensora-0.jpg', '/exercicios/cadeira-extensora-1.jpg', 'Dois segundos na descida, um no topo.'),
  ('bulgaro', 'Agachamento búlgaro', 'halteres', 'Quadríceps', '/exercicios/bulgaro-0.jpg', '/exercicios/bulgaro-1.jpg', 'Tronco 15 a 20° à frente para levar mais carga ao glúteo.'),
  ('step-up', 'Step-up alto', 'halteres', 'Glúteo máximo', '/exercicios/step-up-0.jpg', '/exercicios/step-up-1.jpg', 'Suba empurrando pelo calcanhar, sem impulsionar com a perna de trás.'),
  ('panturrilha-em-pe', 'Panturrilha em pé', 'máquina', 'Panturrilha', '/exercicios/panturrilha-em-pe-0.jpg', '/exercicios/panturrilha-em-pe-1.jpg', 'Pausa de um segundo embaixo.'),
  ('panturrilha-sentada', 'Panturrilha sentada', 'máquina', 'Panturrilha', '/exercicios/panturrilha-sentada-0.jpg', '/exercicios/panturrilha-sentada-1.jpg', 'Pausa de um segundo embaixo.'),
  ('remada-curvada-halteres', 'Remada curvada com halteres', 'halteres', 'Costas', '/exercicios/remada-curvada-halteres-0.jpg', '/exercicios/remada-curvada-halteres-1.jpg', 'Puxe para o quadril com as escápulas retraídas. Um segundo no final.'),
  ('remada-baixa-sentada', 'Remada baixa sentada', 'polia', 'Costas', '/exercicios/remada-baixa-sentada-0.jpg', '/exercicios/remada-baixa-sentada-1.jpg', 'Pegada neutra, escápulas retraídas.'),
  ('serrote', 'Serrote com halter', 'halteres', 'Costas', '/exercicios/serrote-0.jpg', '/exercicios/serrote-1.jpg', 'Cotovelo junto ao corpo, puxando para o quadril.'),
  ('remada-unilateral-maquina', 'Remada unilateral na máquina', 'máquina', 'Costas', '/exercicios/remada-unilateral-maquina-0.jpg', '/exercicios/remada-unilateral-maquina-1.jpg', 'Cotovelo junto ao corpo.'),
  ('supino-halteres', 'Supino com halteres', 'halteres', 'Peito', '/exercicios/supino-halteres-0.jpg', '/exercicios/supino-halteres-1.jpg', 'Escápulas retraídas, cotovelos a uns 45°.'),
  ('supino-maquina', 'Supino na máquina', 'máquina', 'Peito', '/exercicios/supino-maquina-0.jpg', '/exercicios/supino-maquina-1.jpg', 'Escápulas retraídas.'),
  ('supino-inclinado-halteres', 'Supino inclinado com halteres', 'halteres', 'Peito', '/exercicios/supino-inclinado-halteres-0.jpg', '/exercicios/supino-inclinado-halteres-1.jpg', 'Banco a 30°.'),
  ('supino-inclinado-maquina', 'Supino inclinado na máquina', 'máquina', 'Peito', '/exercicios/supino-inclinado-maquina-0.jpg', '/exercicios/supino-inclinado-maquina-1.jpg', 'Banco a 30°.'),
  ('face-pull', 'Face pull na polia', 'polia', 'Deltoide posterior', '/exercicios/face-pull-0.jpg', '/exercicios/face-pull-1.jpg', 'Corda na altura do rosto, cotovelos altos, rotação externa no final.'),
  ('desenvolvimento-halteres', 'Desenvolvimento com halteres', 'halteres', 'Ombro', '/exercicios/desenvolvimento-halteres-0.jpg', '/exercicios/desenvolvimento-halteres-1.jpg', 'Glúteo contraído, costela fechada.'),
  ('desenvolvimento-maquina', 'Desenvolvimento na máquina', 'máquina', 'Ombro', '/exercicios/desenvolvimento-maquina-0.jpg', '/exercicios/desenvolvimento-maquina-1.jpg', 'Costela fechada.'),
  ('crucifixo-inverso', 'Crucifixo inverso', 'halteres', 'Deltoide posterior', '/exercicios/crucifixo-inverso-0.jpg', '/exercicios/crucifixo-inverso-1.jpg', 'Dois segundos na volta. É postura, não volume.'),
  ('crucifixo-inverso-maquina', 'Crucifixo inverso na máquina', 'máquina', 'Deltoide posterior', '/exercicios/crucifixo-inverso-maquina-0.jpg', '/exercicios/crucifixo-inverso-maquina-1.jpg', 'Dois segundos na volta.'),
  ('elevacao-lateral', 'Elevação lateral', 'halteres', 'Deltoide lateral', '/exercicios/elevacao-lateral-0.jpg', '/exercicios/elevacao-lateral-1.jpg', 'Dose de manutenção, de propósito. Não precisa crescer aqui.'),
  ('triceps-polia', 'Tríceps na polia', 'polia', 'Tríceps', '/exercicios/triceps-polia-0.jpg', '/exercicios/triceps-polia-1.jpg', 'Cotovelos parados ao lado do corpo.'),
  ('triceps-testa', 'Tríceps testa', 'halteres', 'Tríceps', '/exercicios/triceps-testa-0.jpg', '/exercicios/triceps-testa-1.jpg', 'Cotovelos apontados para o teto.'),
  ('rosca-halteres', 'Rosca com halteres', 'halteres', 'Bíceps', '/exercicios/rosca-halteres-0.jpg', '/exercicios/rosca-halteres-1.jpg', 'Sem balanço de tronco.'),
  ('rosca-alternada', 'Rosca alternada', 'halteres', 'Bíceps', '/exercicios/rosca-alternada-0.jpg', '/exercicios/rosca-alternada-1.jpg', 'Sem balanço de tronco.'),
  ('rosca-maquina', 'Rosca na máquina', 'máquina', 'Bíceps', '/exercicios/rosca-maquina-0.jpg', '/exercicios/rosca-maquina-1.jpg', 'Braço colado no apoio.'),
  ('abdominal-solo', 'Abdominal no solo', 'peso do corpo', 'Core', '/exercicios/abdominal-solo-0.jpg', '/exercicios/abdominal-solo-1.jpg', 'Sem puxar o pescoço com as mãos.'),
  ('abdominal-maquina', 'Abdominal na máquina', 'máquina', 'Core', '/exercicios/abdominal-maquina-0.jpg', '/exercicios/abdominal-maquina-1.jpg', 'Movimento vem da coluna, não do quadril.'),
  ('prancha', 'Prancha', 'peso do corpo', 'Core', '/exercicios/prancha-0.jpg', '/exercicios/prancha-1.jpg', 'Glúteo contraído, quadril na linha dos ombros.'),
  ('dead-bug', 'Dead bug', 'peso do corpo', 'Core', '/exercicios/dead-bug-0.jpg', '/exercicios/dead-bug-1.jpg', 'Lombar colada no chão o tempo inteiro.');
